---
 - hosts: loadbalancer
   become: TRUE
   vars_files: 
        - secret
   tasks:
       - name: verify nginx service
         command: service nginx status

       - name: verify nginx is listening on 80
         wait_for: port=80 timeout=1


 - hosts: webserver 
   become: TRUE
   vars_files: 
        - secret
   tasks:
       - name: verify apache2 service
         command: service apache2 status

       - name: verify apache2 is listening on 80
         wait_for: port=80 timeout=1

 
 - hosts: database 
   become: TRUE
   vars_files: 
        - secret
   tasks:
       - name: verify mysql service
         command: service mysql status

       - name: verify mysql is listening on 3306 
         wait_for: host={{ansible_ens192.ipv4.address}} port=3306 timeout=1


 - hosts: control
   tasks: 
       - name: verify end-to-end response
         uri: url=http://{{item}} return_content=yes
         with_items: groups.loadbalancer 
         register: lb_index


       - fail: msg="index failed to return content"
         when: "'Hello, from sunny' not in item.content"
         with_items: "{{lb_index.results}}"

 - hosts: loadbalancer
   become: TRUE
   vars_files:
       - secret
   tasks: 
       - name: verify backend response
         uri: url=http://{{item}} return_content=yes
         with_items: groups.webserver 
         register: app_index


       - fail: msg="index failed to return content"
         when: "'Hello, from sunny {{item.item}}' not in item.content"
         with_items: "{{app_index.results}}"
 
